services:
  postgres:
    image: postgres:17
    container_name: calorie_bot_postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: calorie_bot
      POSTGRES_USER: calorie_user
      POSTGRES_PASSWORD: calorie_password

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: