"""Add fiber to nutrition

Revision ID: 093a547d30aa
Revises: 6767a6cd0d6f
Create Date: 2026-08-05 11:58:32.455739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '093a547d30aa'
down_revision: Union[str, Sequence[str], None] = '6767a6cd0d6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nutrition_entries', sa.Column('fiber', sa.Float(), server_default='0', nullable=False))
    op.add_column('products', sa.Column('fiber_100g', sa.Float(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'fiber_100g')
    op.drop_column('nutrition_entries', 'fiber')
    # ### end Alembic commands ###
