"""Add exercises and link workout sets

Revision ID: 5d380e563a40
Revises: 
Create Date: 2026-08-02 22:11:46.974518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d380e563a40'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercises_user_id'), 'exercises', ['user_id'], unique=False)
    op.add_column('workout_sets', sa.Column('exercise_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_workout_sets_exercise_id'), 'workout_sets', ['exercise_id'], unique=False)
    op.create_foreign_key(None, 'workout_sets', 'exercises', ['exercise_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workout_sets', type_='foreignkey')
    op.drop_index(op.f('ix_workout_sets_exercise_id'), table_name='workout_sets')
    op.drop_column('workout_sets', 'exercise_id')
    op.drop_index(op.f('ix_exercises_user_id'), table_name='exercises')
    op.drop_table('exercises')
    # ### end Alembic commands ###
