"""Add fiber display setting

Revision ID: 6767a6cd0d6f
Revises: 5d380e563a40
Create Date: 2026-08-05 11:44:42.602339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6767a6cd0d6f'
down_revision: Union[str, Sequence[str], None] = '5d380e563a40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('show_fiber', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'show_fiber')
    # ### end Alembic commands ###
