"""Add meal type to nutrition entries

Revision ID: 81c2e1e47925
Revises: e0a6880a187e
Create Date: 2026-08-05 21:50:48.695329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81c2e1e47925'
down_revision: Union[str, Sequence[str], None] = 'e0a6880a187e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nutrition_entries', sa.Column('meal_type', sa.String(length=16), server_default='snack', nullable=False))
    op.create_index(op.f('ix_nutrition_entries_meal_type'), 'nutrition_entries', ['meal_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nutrition_entries_meal_type'), table_name='nutrition_entries')
    op.drop_column('nutrition_entries', 'meal_type')
    # ### end Alembic commands ###
