"""Add dishes and ingredients

Revision ID: 9d1601018ac9
Revises: 093a547d30aa
Create Date: 2026-08-05 12:06:27.781021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d1601018ac9'
down_revision: Union[str, Sequence[str], None] = '093a547d30aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dishes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dishes_user_id'), 'dishes', ['user_id'], unique=False)
    op.create_table('dish_ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dish_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('grams', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['dish_id'], ['dishes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dish_ingredients_dish_id'), 'dish_ingredients', ['dish_id'], unique=False)
    op.create_index(op.f('ix_dish_ingredients_product_id'), 'dish_ingredients', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dish_ingredients_product_id'), table_name='dish_ingredients')
    op.drop_index(op.f('ix_dish_ingredients_dish_id'), table_name='dish_ingredients')
    op.drop_table('dish_ingredients')
    op.drop_index(op.f('ix_dishes_user_id'), table_name='dishes')
    op.drop_table('dishes')
    # ### end Alembic commands ###
